### PR TITLE
Add opm common to prereqs

### PR DESCRIPTION
**Pull request by andlaus**
this restores dunecontrol compatibility and prepares the module for the addition of c++ code.

### CODE REVIEW

**Comment by akva2** [comment]
hmm, i chose to keep the OPM_CMAKE_ROOT cmake variable to lessen breakage in the other pr's.

**Comment by akva2** [comment]
@atgeirr since this is now done we may as well include it no ?

**Comment by akva2** [comment]
tested it and it works fine. let's include it.

**Comment by andlaus** [comment]
thanks. I think that keeping the old OPM_CMAKE_ROOT variable name is at best very confusing and it may cause problems if the opm-common find module is to be called (not sure about the latter, though)...

**Comment by akva2** [comment]
it wouldn't cause problems as we set the variable explicitly in the config file. i guess that also needs to be adapted.

**Comment by atgeirr** [comment]
> @atgeirr since this is now done we may as well include it no ?

OK, I'll not stand in the way...

**Comment by atgeirr** [comment]
The OPM_CMAKE_ROOT variable issue was discussed briefly on the mailing list, only a single person replied to my question: Roland said he preferred not to change it, since it locates the build system and not a module as such. So with one vote for and none against that is what we do...

We can raise the issue next, but for now we keep it as is.

**Comment by andlaus** [comment]
let's rename it back to OPM_CMAKE_ROOT if there are major obstacles?

**Comment by akva2** [comment]
yes, let's just do that.

**Comment by andlaus** [comment]
(with a emphasis on the _if_ ;))

**Comment by atgeirr** [comment]
About OPM_CMAKE/COMMON_ROOT: I misunderstood, I did not notice that you had changed it already. This is a coup...

Make the proposal in the main PR to opm-common, to change this, and write a short note about it to warn people (I only think I see this discussion because I was tagged). Then if anyone objects we can have a discussion. Otherwise we go ahead (but that change requires further changes to all other repos, right).

**Comment by andlaus** [comment]
I actually would rather like to avoid making PRs for all 20 (or so) modules again. in the long term, it was planed to change this to `OPM_COMMON_ROOT` anyway, right?

I wouldn't mind writing the notification to the ML, though.

**Comment by atgeirr** [comment]
> I wouldn't mind writing the notification to the ML, though.

We should do this after the change has been discussed (or nobody objected within reasonable time), and we have merged it all. I was planning on doing this myself as I sort-of promised it last week...

**Pull request merged**
